#!/bin/env zsh

gh issue create --body "" --title "feat: add guide about PRs"
gh issue create --body "" --title "fix: update git-server heading"	 -l "easy"
gh issue create --body "" --title "feat: Add new reference for Merkle trees"	 -l enhancement,hard
gh issue create --body "" --title "fix: Reformat \"Conventions\" section"	 -l "easy"
gh issue create --body "" --title "feat: Add paragraphs in \"Implementations\" section"	 -l "easy"
gh issue create --body "" --title "feat: Reformat \"external links\" section as bulleted list"	 -l "easy"
gh issue create --body "" --title "feat: Update formatting of \"Extensions\" section"	 -l "hard"
gh issue create --body "" --title "feat: Add paragraphs in characteristics section"	 -l "easy"
gh issue create --body "" --title "feat: Embed image of Linus in history section"	 -l "extra hard"
gh issue create --body "" --title "feat: Add link to Git-scm website after the page title"	 -l "hard"
gh issue create --body "" --title "fix: Add link to \"comparison of Git GUIs\" on Wikipedia, in the corresponding place"	 -l "hard"
gh issue create --body "" --title "fix: Reformat References section 12/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 11/12"	 -l "medium"
gh issue create --body "" --title "feat: Format the \"Trademark\" section"	 -l "easy"
gh issue create --body "" --title "feat: Add Releases section"	 -l "extra hard"
gh issue create --body "" --title "fix: Reformat References section 10/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 9/12"	 -l "medium"
gh issue create --body "" --title "feat: Add the image to the \"Data Structures\" section"	 -l "hard"
gh issue create --body "" --title "fix: Reformat References section 8/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 7/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 6/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 5/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 4/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat section on \"merging strategies\" in Design: Characteristics"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 3/12"	 -l "medium"
gh issue create --body "" --title "fix: H2 headings"	 -l "easy"
gh issue create --body "" --title "feat: reformat inset section \"Strong support for non-linear development\""	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 2/12"	 -l "medium"
gh issue create --body "" --title "fix: Reformat References section 1/12"	 -l "medium"
gh issue create --body "" --title "fix: H1 headings"	 -l "easy"
gh issue create --body "" --title "feat: Reformat list of names in \"Naming\" section as markdown list"	 -l "easy"
gh issue create --body "" --title "feat: Reformat list of goals in \"history\" section into a formatted list"	 -l "easy"
